# Generated by Django 2.0 on 2018-04-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField(default=100)),
                ('origin_date', models.DateField(auto_now_add=True)),
                ('last_issued', models.DateField(auto_now=True)),
                ('current_status', models.CharField(choices=[('IN', 'Inside'), ('OUT', 'Outside')], default='IN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_start', models.DateField(auto_now_add=True)),
                ('issue_end', models.DateField(auto_now=True)),
                ('current_status', models.CharField(choices=[('IN', 'Inside'), ('OUT', 'Outside')], default='IN', max_length=3)),
                ('late_fee', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian_name', models.TextField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('relevance_date', models.DateField(auto_now_add=True)),
                ('magazine_category', models.ManyToManyField(to='my_library.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('news_category', models.ManyToManyField(to='my_library.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=50)),
                ('pub_addr', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipent_name', models.CharField(max_length=100)),
                ('receipent_advance', models.FloatField(default=0)),
                ('registrant_type', models.CharField(choices=[('STDNT', 'Student'), ('STAFF', 'Staff')], default='STDNT', max_length=9)),
                ('email_id', models.EmailField(max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_library.Librarian'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_receipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_library.Receipent'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ManyToManyField(to='my_library.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_library.Publisher'),
        ),
    ]
