# Generated by Django 2.0 on 2018-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_receipent',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_start',
            field=models.DateField(),
        ),
    ]
